### ISSUE TITLE
Update homepage video for H5BP 6.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5boilerplate.com#157]
It'd be great to get a new video for the imminent 6.0 release.

It might not make sense to keep the 'An Introduction to HTML5 Boilerplate v5.0' video on the homepage once v6 ships.

**Comment by roblarsen** [comment]
I have created a branch for this work [six-dot-oh](https://github.com/h5bp/html5boilerplate.com/tree/six-dot-oh) @coliff base any work on a new version off of that branch and we'll push everything at once once we're ready. 

I would surely like to do a video, but I am also obsessed with just shipping this code, so, we'll see.

**Comment by coliff** [comment]
Great stuff. Will make a PR to update the index.html soon. Note to self for changes:

- [ ] External links should have `rel=noopener` (for improved security and performance)
- [ ] Change `apple-touch-icon.png` to `icon.png`
- [ ] Change http://modernizr.com/ link to https
- [ ] Add `site.webmanifest` file
- [ ] Remove v5 video? (info will be outdated once v6 lands)
- [ ] Consider adding Twitter card and Facebook Open Graph meta tags to head?
- [ ] Remove broken link to: http://www.projectrebrief.com/   (#159)
- [ ] Update the jQuery CDN (#158)
- [ ] main.js should specify always loading Google Analytics via HTTPS

Also needs to be fixed:
- [ ] CSP Errors for loading favicon.ico and apple-touch-icon.png  (#147)

**Comment by roblarsen** [comment]
I've got an idea for a simple video, I'll take a shot this week at putting something together.

**Comment by roblarsen** [comment]
I updated [six-dot-oh](https://github.com/h5bp/html5boilerplate.com/tree/six-dot-oh) with some basic content. I'm not sure about getting a video in place immediately (@paulirish who owns the Youtube channel if I get seriously enthusiastic?) so I  just wanted to get some content on there that makes sense.

**Comment by roblarsen** [comment]
I'm keeping this issue open for a while. The site is updated so that the download links are set up right, but I'd like to continue to tinker for a little while at least to actually get the site refreshed a little bit.

**Comment by JPOak** [comment]
I noticed that the download link/button on the website is for in older tag/version. Is this supposed to be like this ? It's downloading 5.3 . I got a little confused .
